# -*- coding: utf-8 -*-
"""CreditCardFraudDetection

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16EPBee4FmvsI5pvG2T13UUgJOwkZhYbT
"""

!pip install --upgrade kaggle

# Create a hidden directory named .kaggle
!mkdir ~/.kaggle

# Copy the Kaggle API key to the .kaggle directory
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

# Force download the dataset from Kaggle
!kaggle datasets download -d mlg-ulb/creditcardfraud --force

# Unzip the downloaded file and overwrite existing files without prompting
!unzip -o creditcardfraud.zip

# Import necessary libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import RobustScaler
from sklearn.metrics import auc
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import LinearSVC
from sklearn.metrics import classification_report, confusion_matrix, roc_curve, roc_auc_score
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import InputLayer, Dense, BatchNormalization
from tensorflow.keras.callbacks import ModelCheckpoint
import seaborn as sns
import matplotlib.pyplot as plt

# Load your dataset
df = pd.read_csv('creditcard.csv')

# Bar plot of class distribution with counts on the bars
plt.figure(figsize=(8, 6))
ax = sns.countplot(x='Class', data=df, palette='viridis', hue='Class', dodge=False)

# Annotate the counts on the bars
for p in ax.patches:
    ax.annotate(f'{p.get_height()}', (p.get_x() + p.get_width() / 2., p.get_height()),
                ha='center', va='center', xytext=(0, 9), textcoords='offset points')

plt.title('Class Distribution')
plt.xlabel('Class')
plt.ylabel('Count')
plt.xticks([0, 1], ['Not Fraud', 'Fraud'])
plt.legend([],[], frameon=False)  # Remove the redundant legend
plt.show()

# Load your dataset
df = pd.read_csv('creditcard.csv')

# Calculate the correlation matrix
correlation_matrix = df.corr()

# Plot the correlation matrix as a heatmap
plt.figure(figsize=(15, 10))
sns.heatmap(correlation_matrix, annot=True,fmt='.0f', cmap='coolwarm', linewidths=0.5)
plt.title('Correlation Matrix')
plt.show()

#Generate histograms for each column in the DataFrame 'df'
df.hist(bins=30, figsize=(30, 30))

# Generate descriptive statistics for each numerical column in the DataFrame 'df'
df.describe()

# Create a copy of the DataFrame 'df' to avoid modifying the original data
new_df = df.copy()

# Apply RobustScaler to the 'Amount' column to scale it
new_df['Amount'] = RobustScaler().fit_transform(new_df['Amount'].to_numpy().reshape(-1, 1))

# Normalize the 'Time' column to a range between 0 and 1
time = new_df['Time']
new_df['Time'] = (time - time.min()) / (time.max() - time.min())

# Display the modified DataFrame 'new_df' to see the scaled 'Amount' and normalized 'Time' columns
new_df

def preprocess_data(df):


    # Create a copy of the DataFrame to avoid modifying the original data
    new_df = df.copy()

    # Apply RobustScaler to the 'Amount' column to scale it
    new_df['Amount'] = RobustScaler().fit_transform(new_df['Amount'].to_numpy().reshape(-1, 1))

    # Normalize the 'Time' column to a range between 0 and 1
    time = new_df['Time']
    new_df['Time'] = (time - time.min()) / (time.max() - time.min())

    return new_df
df = preprocess_data(df)
df = df.sample(frac=1, random_state=1)  # Shuffle the dataset

# Split the data into training, testing, and validation sets
train, test, val = df[:240000], df[240000:262000], df[262000:]
x_train, y_train = train.iloc[:, :-1], train.iloc[:, -1]
x_test, y_test = test.iloc[:, :-1], test.iloc[:, -1]
x_val, y_val = val.iloc[:, :-1], val.iloc[:, -1]

# Function to train and evaluate a Logistic Regression model
def logistic_regression(x_train, y_train, x_val, y_val):
    model = LogisticRegression(max_iter=1000)
    model.fit(x_train, y_train)
    y_pred = model.predict(x_val)
    print(classification_report(y_val, y_pred, target_names=['Not Fraud', 'Fraud']))
    return model

logistic_model = logistic_regression(x_train, y_train, x_val, y_val)

# Function to build, train, and evaluate a shallow neural network
def build_shallow_nn(input_shape):
    model = Sequential([
        InputLayer(input_shape=input_shape),
        Dense(2, activation='relu'),
        BatchNormalization(),
        Dense(1, activation='sigmoid')
    ])
    model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
    return model

shallow_nn = build_shallow_nn(x_train.shape[1])
checkpoint = ModelCheckpoint('shallow_nn', save_best_only=True)
shallow_nn.fit(x_train, y_train, validation_data=(x_val, y_val), epochs=5, callbacks=[checkpoint])

# Neural Network model
shallow_nn = Sequential()
shallow_nn.add(InputLayer((x_train.shape[1],)))
shallow_nn.add(Dense(2, 'relu'))
shallow_nn.add(BatchNormalization())
shallow_nn.add(Dense(1, 'sigmoid'))
checkpoint = ModelCheckpoint('shallow_nn', save_best_only=True)
shallow_nn.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
shallow_nn.fit(x_train, y_train, validation_data=(x_val, y_val), epochs=5, callbacks=[checkpoint])

# Function to plot confusion matrix
def plot_confusion_matrix(y_true, y_pred, labels):
    cm = confusion_matrix(y_true, y_pred)
    plt.figure(figsize=(6, 4))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=labels, yticklabels=labels)
    plt.xlabel('Predicted Label')
    plt.ylabel('True Label')
    plt.title('Confusion Matrix')
    plt.show()

# Function to plot ROC curve
def plot_roc_curve(y_true, y_prob, model_name):
    fpr, tpr, thresholds = roc_curve(y_true, y_prob)
    roc_auc = auc(fpr, tpr)
    plt.figure(figsize=(6, 4))
    plt.plot(fpr, tpr, color='orange', lw=2, label=f'{model_name} (AUC = {roc_auc:.2f})')
    plt.plot([0, 1], [0, 1], color='blue', linestyle='--')
    plt.xlabel('False Positive Rate')
    plt.ylabel('True Positive Rate')
    plt.title(f'ROC Curve - {model_name}')
    plt.legend()
    plt.show()

def neural_net_predictions(model, x):
    return (model.predict(x).flatten() > 0.5).astype(int)

print(classification_report(y_val, neural_net_predictions(shallow_nn, x_val), target_names=['Not Fraud', 'Fraud']))
# Generate confusion matrix and ROC curve for Shallow Neural Network model
nn_probs = shallow_nn.predict(x_val).flatten()
nn_preds = neural_net_predictions(shallow_nn, x_val)
plot_confusion_matrix(y_val, nn_preds, ['Not Fraud', 'Fraud'])
plot_roc_curve(y_val, nn_probs, 'Shallow Neural Network')

# RandomForest model
rf = RandomForestClassifier(max_depth=2, n_jobs=-1)
rf.fit(x_train, y_train)
print(classification_report(y_val, rf.predict(x_val), target_names=['Not Fraud', 'Fraud']))
# Generate confusion matrix and ROC curve for RandomForestClassifier model
rf_probs = rf.predict_proba(x_val)[:, 1]
rf_preds = rf.predict(x_val)
plot_confusion_matrix(y_val, rf_preds, ['Not Fraud', 'Fraud'])
plot_roc_curve(y_val, rf_probs, 'Random Forest Classifier')

# GradientBoostingClassifier model
gbc = GradientBoostingClassifier(n_estimators=50, learning_rate=1.0, max_depth=1, random_state=0)
gbc.fit(x_train, y_train)
print(classification_report(y_val, gbc.predict(x_val), target_names=['Not Fraud', 'Fraud']))
# Generate confusion matrix and ROC curve for GradientBoostingClassifier model
gbc_probs = gbc.predict_proba(x_val)[:, 1]
gbc_preds = gbc.predict(x_val)
plot_confusion_matrix(y_val, gbc_preds, ['Not Fraud', 'Fraud'])
plot_roc_curve(y_val, gbc_probs, 'Gradient Boosting Classifier')

# LinearSVC model
svc_unbalanced = LinearSVC()  # Increase max_iter to avoid convergence issues
svc_unbalanced.fit(x_train, y_train)
y_pred_unbalanced = svc_unbalanced.predict(x_val)

# Print the classification report
print(classification_report(y_val, y_pred_unbalanced, target_names=['Not Fraud', 'Fraud']))

# Generate confusion matrix and ROC curve for LinearSVC
svc_probs = svc_unbalanced.decision_function(x_val)  # Using decision_function for LinearSVC
svc_preds = svc_unbalanced.predict(x_val)
plot_confusion_matrix(y_val, svc_preds, ['Not Fraud', 'Fraud'])
plot_roc_curve(y_val, svc_probs, 'Linear SVC')

# Balancing the dataset
not_frauds = df.query('Class == 0')
frauds = df.query('Class == 1')

balanced_df = pd.concat([frauds, not_frauds.sample(len(frauds), random_state=1)]).sample(frac=1, random_state=1)

# Split balanced data into training, testing, and validation sets
balanced_df_np = balanced_df.to_numpy()
x_train_b, y_train_b = balanced_df_np[:700, :-1], balanced_df_np[:700, -1].astype(int)
x_test_b, y_test_b = balanced_df_np[700:842, :-1], balanced_df_np[700:842, -1].astype(int)
x_val_b, y_val_b = balanced_df_np[842:, :-1], balanced_df_np[842:, -1].astype(int)

# Train and evaluate Logistic Regression model on balanced data
logistic_model_b = LogisticRegression()
logistic_model_b.fit(x_train_b, y_train_b)
print(classification_report(y_val_b, logistic_model_b.predict(x_val_b), target_names=['Not Fraud', 'Fraud']))
#Generate confusion matrix and ROC curve for Logistic Regression model
logistic_probs = logistic_model.predict_proba(x_val)[:, 1]
logistic_preds = logistic_model.predict(x_val)
plot_confusion_matrix(y_val, logistic_preds, ['Not Fraud', 'Fraud'])
plot_roc_curve(y_val, logistic_probs, 'Logistic Regression')

# Train and evaluate balanced shallow neural network model
shallow_nn_b = Sequential()
shallow_nn_b.add(InputLayer((x_train.shape[1],)))
shallow_nn_b.add(Dense(2, 'relu'))
shallow_nn_b.add(BatchNormalization())
shallow_nn_b.add(Dense(1, 'sigmoid'))
checkpoint = ModelCheckpoint('shallow_nn_b', save_best_only=True)
shallow_nn_b.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
shallow_nn_b.fit(x_train_b, y_train_b, validation_data=(x_val_b, y_val_b), epochs=40, callbacks=[checkpoint])
print(classification_report(y_val_b, neural_net_predictions(shallow_nn_b, x_val_b), target_names=['Not Fraud', 'Fraud']))

# Train and evaluate RandomForest model on balanced data
rf_b = RandomForestClassifier(max_depth=2, n_jobs=-1)
rf_b.fit(x_train_b, y_train_b)
print(classification_report(y_val_b, rf_b.predict(x_val_b), target_names=['Not Fraud', 'Fraud']))

# Train and evaluate GradientBoostingClassifier model on balanced data
gbc_b = GradientBoostingClassifier(n_estimators=50, learning_rate=1.0, max_depth=2, random_state=0)
gbc_b.fit(x_train_b, y_train_b)
print(classification_report(y_val_b, gbc_b.predict(x_val_b), target_names=['Not Fraud', 'Fraud']))

# Train and evaluate LinearSVC model on balanced data
svc_b = LinearSVC(class_weight='balanced')
svc_b.fit(x_train_b, y_train_b)
y_pred_b = svc_b.predict(x_val_b)
print(classification_report(y_val_b, y_pred_b, target_names=['Not Fraud', 'Fraud']))

# Evaluate shallow neural network on balanced test data
print(classification_report(y_test_b, neural_net_predictions(shallow_nn_b, x_test_b), target_names=['Not Fraud', 'Fraud']))